# Generated by Django 2.0.6 on 2019-02-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calfit', '0009_auto_20190205_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_repond_no',
            new_name='message_respond_no',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_repond_yes',
            new_name='message_respond_yes',
        ),
    ]
