# Generated by Django 2.0.6 on 2019-01-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calfit', '0002_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
