# Generated by Django 2.0.6 on 2019-01-30 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calfit', '0004_auto_20190130_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 30, 17, 58, 37, 512075, tzinfo=utc)),
        ),
    ]
