# Generated by Django 2.0.6 on 2019-02-05 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calfit', '0006_auto_20190203_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 5, 6, 8, 32, 854127, tzinfo=utc)),
        ),
    ]
