# Generated by Django 2.0.6 on 2019-02-05 22:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calfit', '0007_auto_20190205_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('type', models.IntegerField(default=0)),
                ('responded', models.BooleanField(default=False)),
                ('message_title', models.CharField(default=None, max_length=100)),
                ('message_content', models.CharField(default=None, max_length=500)),
                ('message_repond_yes', models.CharField(default=None, max_length=500)),
                ('message_repond_no', models.CharField(default=None, max_length=500)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 5, 22, 20, 27, 224535, tzinfo=utc)),
        ),
    ]
